### ISSUE TITLE
No mapping to the Request object

### ISSUE THREAD

**Issue by TimothyGillespie** [JavaWebStack/HTTP-Server#5]
**Describe the Bug**
When using the Body Annotation the request body object will map 1:1 with the request body and no mapping occurs.   

**To Reproduce**
Create an endpoint with the Body Annotation and see what request body reaches the object given. 

**Expected behavior**
It should use the inverse mapping of the Response object mapping.

**Screenshots / Logs**
If applicable, add screenshots and/or logs to help explain your problem. You can use pastefy.ga to upload large text snippets.

**Environment Information:**
 - Java Language Level 11

**Additional Context**
@JulianFun123 Can confirm the error

**Comment by JulianFun123** [comment]
Set naming policies from default to camel_case

**Comment by TimothyGillespie** [comment]
Unfortunately, it seems like it didn't fix the issue.

**Comment by TimothyGillespie** [comment]
At some point some solved magically.
