### ISSUE TITLE
Exclude the application of middleware on certain routes

### ISSUE THREAD

**Issue by TimothyGillespie** [JavaWebStack/HTTP-Server#8]
**Is your feature request related to a problem? Please describe.**
This is useful, for example, when you have a login route and an authentication middleware. You don't want people required to be logged in so they can login. Same with registrations.

**Describe the solution you'd like**
A method on the HTTPServer which allows to register exceptions when not to use the middleware, similar to how the middleware are put is in `.beforeAny(...)`.

Another idea would be to have a method on the middleware object which returns an String array with those exceptions or pattern of those exceptions.

Another solution might be to introduce a method on the middleware object which returns a boolean which is true if is should not be applied and false if it should. I think I'd even prefer this one though I'm not sure how efficient this one can be.

**Describe alternatives you've considered**
Define your own list of exception in the middleware and skip manually. I find it very inconvenient and doesn't seem ideal to reimplement this - all be it a small - logic.

**Additional context**
None

**Comment by JanHolger** [comment]
We already have named middlewares for this specific use case. They can be registered using the middleware methods on the HTTPServer class and apply rules to controllers or single routes using the @With annotation. The middleware system isn't perfect yet and we are still searching for a proper way to implement them that covers as much cases as possible while being easy to use but for now named middlewares are the goto solution for the proposed issue.
